let currentLang='ar';
function money(n){return Number(n||0).toLocaleString(currentLang==='ar'?'ar-SA':'en-US',{maximumFractionDigits:2})+' '+(currentLang==='ar'?'ر.س':'SAR')}
function qs(n){return document.querySelector(`[name="${n}"]`)}
function showPage(id,el){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active-page'));document.getElementById(id).classList.add('active-page');document.querySelectorAll('.nav-link').forEach(a=>a.classList.remove('active'));if(el)el.classList.add('active');location.hash=id;if(id==='students')loadStudentsTable();if(id==='installments')loadInstallments();if(id==='reports')loadReports()}
function toggleLang(){currentLang=currentLang==='ar'?'en':'ar';document.documentElement.lang=currentLang;document.documentElement.dir=currentLang==='ar'?'rtl':'ltr';document.getElementById('langBtn').textContent=currentLang==='ar'?'English':'عربي';document.querySelectorAll('[data-ar][data-en]').forEach(e=>{e.textContent=e.dataset[currentLang]});}
function calcPreview(){const tuition=+qs('tuition').value||0, reg=+qs('registration_fee').value||0, discount=+qs('discount').value||0, vatp=+qs('vat_percent').value||0, count=+qs('installments_count').value||1;const subtotal=tuition+reg-discount, vat=subtotal*vatp/100,total=subtotal+vat;document.getElementById('previewSubtotal').textContent=money(subtotal);document.getElementById('previewVat').textContent=money(vat);document.getElementById('previewTotal').textContent=money(total);document.getElementById('previewInstallment').textContent=money(total/count);return{subtotal,vat,total,count}}
document.querySelectorAll('.calc').forEach(e=>e.addEventListener('input',calcPreview));
async function saveStudent(){try{const c=calcPreview();const student={name_ar:qs('name_ar').value,name_en:qs('name_en').value,national_id:qs('national_id').value,gender:qs('gender').value,stage:qs('stage').value,grade:qs('grade').value,class_name:qs('class_name').value,admission_date:qs('admission_date').value,guardian_name:qs('guardian_name').value,guardian_mobile:qs('guardian_mobile').value,email:qs('email').value,address:qs('address').value,createdAt:firebase.firestore.FieldValue.serverTimestamp()};const contract={academic_year:qs('academic_year').value,tuition:+qs('tuition').value||0,registration_fee:+qs('registration_fee').value||0,discount:+qs('discount').value||0,vat_percent:+qs('vat_percent').value||0,installments_count:+qs('installments_count').value||1,subtotal:c.subtotal,vat_amount:c.vat,contract_total:c.total,createdAt:firebase.firestore.FieldValue.serverTimestamp()};const doc=await db.collection('students').add({student,contract});await generateInstallments(doc.id,student,c.total,contract.installments_count,qs('first_due_date').value);alert(currentLang==='ar'?'تم حفظ الطالب والعقد والأقساط بنجاح':'Student, contract and installments saved');document.querySelector('form').reset();calcPreview();loadDashboard()}catch(e){console.error(e);alert(currentLang==='ar'?'حدث خطأ أثناء الحفظ. تأكد من Firestore Rules':'Save error. Check Firestore rules')}}
async function generateInstallments(studentId,student,total,count,startDate){const batch=db.batch();let base=startDate?new Date(startDate):new Date();if(!startDate)base.setMonth(base.getMonth()+1);for(let i=1;i<=count;i++){let d=new Date(base);d.setMonth(base.getMonth()+(i-1)*2);const ref=db.collection('installments').doc();batch.set(ref,{studentId,studentNameAr:student.name_ar,studentNameEn:student.name_en,installment_no:i,amount:total/count,status:i===1?'paid':'pending',due_date:d.toISOString().slice(0,10),createdAt:firebase.firestore.FieldValue.serverTimestamp()})}await batch.commit()}
async function loadDashboard(){const s=await db.collection('students').get();const ins=await db.collection('installments').get();let contracts=0,collected=0,remaining=0;s.forEach(d=>contracts+=+(d.data().contract?.contract_total||0));ins.forEach(d=>{const x=d.data();if(x.status==='paid')collected+=+x.amount||0;else remaining+=+x.amount||0});document.getElementById('studentsCount').textContent=s.size;document.getElementById('contractsTotal').textContent=money(contracts);document.getElementById('collectedTotal').textContent=money(collected);document.getElementById('collectionRate').textContent=contracts?Math.round(collected/contracts*100)+'%':'0%';document.getElementById('rpStudents').textContent=s.size;document.getElementById('rpContracts').textContent=money(contracts);document.getElementById('rpCollected').textContent=money(collected);document.getElementById('rpRemaining').textContent=money(remaining);await loadRecentStudents();await loadReports()}
async function loadRecentStudents(){const body=document.getElementById('recentStudentsTable');const snap=await db.collection('students').limit(10).get();let html='';snap.forEach(doc=>{const d=doc.data();html+=`<tr><td>${d.student?.name_ar||d.student?.name_en||'-'}</td><td>${d.student?.national_id||'-'}</td><td>${d.student?.grade||'-'}</td><td>${d.student?.class_name||'-'}</td><td>${money(d.contract?.contract_total)}</td></tr>`});body.innerHTML=html||`<tr><td colspan="5">${currentLang==='ar'?'لا توجد بيانات':'No data'}</td></tr>`}
async function loadStudentsTable(){const body=document.getElementById('studentsRows');const snap=await db.collection('students').get();let html='';snap.forEach(doc=>{const d=doc.data();html+=`<tr><td>${d.student?.name_ar||d.student?.name_en||'-'}</td><td>${d.student?.national_id||'-'}</td><td>${d.student?.stage||'-'}</td><td>${d.student?.grade||'-'}</td><td>${d.student?.guardian_name||'-'}</td><td>${d.student?.guardian_mobile||'-'}</td><td>${money(d.contract?.contract_total)}</td></tr>`});body.innerHTML=html||`<tr><td colspan="7">${currentLang==='ar'?'لا توجد بيانات':'No data'}</td></tr>`}
async function loadInstallments(){const body=document.getElementById('installmentsRows');const snap=await db.collection('installments').get();let html='',i=1;snap.forEach(doc=>{const x=doc.data();html+=`<tr><td>${i++}</td><td>${currentLang==='ar'?(x.studentNameAr||x.studentNameEn):(x.studentNameEn||x.studentNameAr)}</td><td>${x.installment_no}</td><td>${x.due_date}</td><td>${money(x.amount)}</td><td><span class="${x.status==='paid'?'badge-paid':'badge-pending'}">${x.status==='paid'?(currentLang==='ar'?'مدفوع':'Paid'):(currentLang==='ar'?'مستحق':'Pending')}</span></td><td>${x.status==='pending'?`<button class="btn btn-sm btn-success" onclick="markPaid('${doc.id}')">${currentLang==='ar'?'تسجيل دفع':'Mark Paid'}</button>`:'-'}</td></tr>`});body.innerHTML=html||`<tr><td colspan="7">${currentLang==='ar'?'لا توجد بيانات':'No data'}</td></tr>`}
async function markPaid(id){await db.collection('installments').doc(id).update({status:'paid',paidAt:firebase.firestore.FieldValue.serverTimestamp()});loadInstallments();loadDashboard()}
async function loadReports(){const body=document.getElementById('dueRows');const snap=await db.collection('installments').where('status','==','pending').get();let html='';snap.forEach(doc=>{const x=doc.data();html+=`<tr><td>${currentLang==='ar'?(x.studentNameAr||x.studentNameEn):(x.studentNameEn||x.studentNameAr)}</td><td>${x.due_date}</td><td>${money(x.amount)}</td><td><span class="badge-pending">${currentLang==='ar'?'مستحق':'Pending'}</span></td></tr>`});body.innerHTML=html||`<tr><td colspan="4">${currentLang==='ar'?'لا توجد أقساط مستحقة':'No due installments'}</td></tr>`}
function printArea(id){const section=document.getElementById(id);const w=window.open('','_blank');w.document.write(`<html dir="${document.documentElement.dir}" lang="${currentLang}"><head><title>Print</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.rtl.min.css" rel="stylesheet"><style>body{font-family:Tahoma;padding:25px}.btn-print-small,.btn-save{display:none}.panel{border:1px solid #ddd;padding:20px;border-radius:12px}.table td,.table th{text-align:center}</style></head><body>${section.outerHTML}</body></html>`);w.document.close();w.print()}
function printUnpaidOnly(){printArea('reports')}
window.addEventListener('load',()=>{calcPreview();loadDashboard();const hash=location.hash.replace('#','');if(hash&&document.getElementById(hash))showPage(hash,document.querySelector(`a[href="#${hash}"]`))});
